FROM centos:latest
MAINTAINER patilyogita5563@gmail.com
RUN yum install -y httpd\
zip
unzip
ADD https://www.free-css.com/free-css-templates/download/page254/phothogenic.zip
WORKDIR /var/www/html/
RUN unzip phothogenic.zip
RUN cp -rvf phothogenic/* .
RUN rm -rf phothogenic phothogenic.zip
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
EXPOSE 80