FROM centos:latest
MAINTAINER patilyogita5563@gmail.com
RUN yum install -y httpd \
 zip\
 unzip
ADD https://www.free-css.com/assets/files/free-css-templates/download/page24/photogenic.zip /var/www/html/
WORKDIR /var/www/html/
RUN unzip phothogenic.zip
RUN cp -rvf phothogenic/* .
RUN rm -rf phothogenic phothogenic.zip
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
EXPOSE 80
